### ISSUE TITLE
Any way I can auto upload images to BunnyCDN and not my host?

### ISSUE THREAD

**Issue by GiacomoLaw** [codewithmark/bunnycdn#2]
Limited on space on my host, so was wondering if this was possible?

Thanks!

**Comment by codewithmark** [comment]
Hi GiacomoLaw,

You can try this to see if it works for you:
Let's say below is your HTML file upload code:
`
<!DOCTYPE html>
<html>
<body>

<form action="upload.php" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>

</body>
</html>
`
Your PHP code will be:

`
include 'bunnycdn.php';

$cdn = new BunnyCDN();

$storage_key = "Your-Storage-Key";

$local_upload_file_path = $_FILES["fileToUpload"];

//path where you want to store your file
$storage_zone_path = '/mybunnycdnsite';

//file name you want to save it as
$storage_zone_file_path = '/my test file-'.uniqid().'.mp4';

$d1 = $cdn->Storage($storage_key)->PutFile($local_upload_file_path, $storage_zone_path, $storage_zone_file_path);

`
Let me if this doesn't work for you and then I will reopen this.

**Comment by GiacomoLaw** [comment]
Great, I will give it a go. Thank you!

**Comment by GiacomoLaw** [comment]
Not really sure how to put this in a plugin - have very limited experience with WP Plugins. :)

**Comment by codewithmark** [comment]
You might want to check this course (https://1estore.com/s/code-with-mark/course/b1b4d0d9) that will teach you how to create a wordpress plugin. 

If you need help in building a custom wordpress plugin, I can you help out with that. You can check out my services section of the site ( https://codewithmark.com/services ) 

Happy Coding :-)

**Comment by GiacomoLaw** [comment]
Thank you!

**Comment by Xarex** [comment]
I created a plugin in collaboration with BunnyCDN and built [BunnyAPI](https://bunnyapi.com) and a plugin to go along with it that lets you upload directly from your website to BunnyCDN. https://wordpress.org/plugins/bunnycdnbunnyapi/

**Comment by adihanifsdr** [comment]
I have a questions

> Hi GiacomoLaw,
> 
> You can try this to see if it works for you:
> Let's say below is your HTML file upload code:
> `
> 
> Select image to upload: ` Your PHP code will be:
> `
> include 'bunnycdn.php';
> 
> $cdn = new BunnyCDN();
> 
> $storage_key = "Your-Storage-Key";
> 
> $local_upload_file_path = $_FILES["fileToUpload"];
> 
> //path where you want to store your file
> $storage_zone_path = '/mybunnycdnsite';
> 
> //file name you want to save it as
> $storage_zone_file_path = '/my test file-'.uniqid().'.mp4';
> 
> $d1 = $cdn->Storage($storage_key)->PutFile($local_upload_file_path, $storage_zone_path, $storage_zone_file_path);
> 
> `
> Let me if this doesn't work for you and then I will reopen this.

I have a question, i implement CloudFlare so there a limit in uploading to my host (only 100mb are allowed). Does by using this code directly upload file to BunnyCDN (User -> BunnyCDN) instead from User-> Host -> BunnyCDN ?
Does $_FILES variables are get from user local or host server?

**Comment by Xarex** [comment]
adihanifsdr, I am not sure who is still active here, but I do actively work on BunnyAPI and with BunnyCDN. If you have your DNS routing through Cloudflare, there is a max of 100 MB for uploads or post processes, and you will get a 504 error from Cloudflare. 

There is no way of getting around this as far as I know unless you can break up the file into bits, but you'd still have to ensure your transfer took less than 100 MB. I've even attempted to make it DNS-only, but anything that passes through Cloudflare will follow these same rules.  They are a bit cheap when it comes to the 100 MB cap and only offer about 100 or 200 MB for the most expensive plan. They are probably capping it to prevent abuse.

$_FILES is what is passed in by the upload form.

You can use this to upload files to your server. 
<form action="upload.php" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>

If you'd prefer the easy route, BunnyAPI handles all of this and there is no max cap limits on any of your uploads.

Sample of a BunnyAPI upload:

https://bunnyapi.com/bunnycdn?key=BunnyAPI&action=upload&folder=bunnyfolder&filename=https://bunnyapi.com/bunnyapi-logo.jpg

This would upload an image file directly to your BunnyCDN.

**Comment by codewithmark** [comment]
> adihanifsdr, I am not sure who is still active here, but I do actively work on BunnyAPI and with BunnyCDN. If you have your DNS routing through Cloudflare, there is a max of 100 MB for uploads or post processes, and you will get a 504 error from Cloudflare.
> 
> There is no way of getting around this as far as I know unless you can break up the file into bits, but you'd still have to ensure your transfer took less than 100 MB. I've even attempted to make it DNS-only, but anything that passes through Cloudflare will follow these same rules. They are a bit cheap when it comes to the 100 MB cap and only offer about 100 or 200 MB for the most expensive plan. They are probably capping it to prevent abuse.
> 
> $_FILES is what is passed in by the upload form.
> 
> You can use this to upload files to your server.
> 
> Select image to upload:
> If you'd prefer the easy route, BunnyAPI handles all of this and there is no max cap limits on any of your uploads.
> 
> Sample of a BunnyAPI upload:
> 
> https://bunnyapi.com/bunnycdn?key=BunnyAPI&action=upload&folder=bunnyfolder&filename=https://bunnyapi.com/bunnyapi-logo.jpg
> 
> This would upload an image file directly to your BunnyCDN.

Hi Xarex,

Unfortunately because you are using Cloudflare for your DNS.... it will prevent any files to be uploaded to your server that are more than 100 MB. 

So, next available option is to send your big files directly to bunnycdn via javascript or jquery. If you are interested in buying the script, you can email be here(https://1estore.com/s1/5d7efc4c).

Happy Coding :-)

Thank

**Comment by ghost** [comment]
@codewithmark Is there a demo video where you can show us the javascript/jquery upload working ?

**Comment by Xarex** [comment]
> Hi Xarex,
> 
> Unfortunately because you are using Cloudflare for your DNS.... it will prevent any files to be uploaded to your server that are more than 100 MB.
> 
> So, next available option is to send your big files directly to bunnycdn via javascript or jquery. If you are interested in buying the script, you can email be here(https://codewithmark.com/contact).
> 
> Happy Coding :-)
> 
> Thank

I have a bunch of websites on Cloudflare but BunnyAPI is not one of them, mark.
