### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by ysb** [codewithmark/bunnycdn#5]
Hi,

Do you consider adding this package to packagist?

**Comment by codewithmark** [comment]
Hi ysb,

To be quit honest with you I don't know how at this moment. 

But if you know and have the time to show me, the community will THANK YOU for it!!

Thanks

Happy Coding :-) 

Mark

**Comment by ysb** [comment]
Hi @codewithmark,

I'm just trying bunnycdn for a project. If i decide to continue with it, i can make a PR for that.

Thanks.

**Comment by codewithmark** [comment]
That would be awesome!
